packages:
  - 'apps/*'
  - 'libs/*'
  - 'shared-kernel/*'

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - '@temporalio/core-bridge'
  - nx
  - protobufjs
  - unrs-resolver
